package channel

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"os"
	"regexp"
	"strings"
	"sync"
	"time"

	common2 "github.com/QuantumNous/new-api/common"
	"github.com/QuantumNous/new-api/logger"
	"github.com/QuantumNous/new-api/relay/common"
	"github.com/QuantumNous/new-api/relay/constant"
	"github.com/QuantumNous/new-api/relay/helper"
	"github.com/QuantumNous/new-api/service"
	"github.com/QuantumNous/new-api/setting/operation_setting"
	"github.com/QuantumNous/new-api/types"

	"github.com/bytedance/gopkg/util/gopool"
	"github.com/gin-gonic/gin"
	"github.com/gorilla/websocket"
)

// applyUpstreamContentLength populates req.ContentLength when the upstream
// body is wrapped in a BodyStorage (see relay/common/outbound_body.go).
//
// net/http.NewRequest only auto-detects ContentLength for *bytes.Reader,
// *bytes.Buffer and *strings.Reader. When the body is a type-erased io.Reader
// (which is the case for ReaderOnly(BodyStorage)), the Content-Length header
// would otherwise be omitted, forcing chunked transfer encoding and breaking
// some upstreams that require an explicit Content-Length.
func applyUpstreamContentLength(req *http.Request, info *common.RelayInfo) {
	if info == nil {
		return
	}
	if info.UpstreamRequestBodySize > 0 && req.ContentLength <= 0 {
		req.ContentLength = info.UpstreamRequestBodySize
	}
}

func SetupApiRequestHeader(info *common.RelayInfo, c *gin.Context, req *http.Header) {
	if info.RelayMode == constant.RelayModeAudioTranscription || info.RelayMode == constant.RelayModeAudioTranslation {
		// multipart/form-data
	} else if info.RelayMode == constant.RelayModeRealtime {
		// websocket
	} else {
		req.Set("Content-Type", c.Request.Header.Get("Content-Type"))
		req.Set("Accept", c.Request.Header.Get("Accept"))
		if info.IsStream && c.Request.Header.Get("Accept") == "" {
			req.Set("Accept", "text/event-stream")
		}
	}
}

const clientHeaderPlaceholderPrefix = "{client_header:"

const (
	headerPassthroughAllKey        = "*"
	headerPassthroughRegexPrefix   = "re:"
	headerPassthroughRegexPrefixV2 = "regex:"
)

var passthroughSkipHeaderNamesLower = map[string]struct{}{
	// RFC 7230 hop-by-hop headers.
	"connection":          {},
	"keep-alive":          {},
	"proxy-authenticate":  {},
	"proxy-authorization": {},
	"te":                  {},
	"trailer":             {},
	"transfer-encoding":   {},
	"upgrade":             {},

	"cookie": {},

	// Additional headers that should not be forwarded by name-matching passthrough rules.
	"host":            {},
	"content-length":  {},
	"accept-encoding": {},

	// Do not passthrough credentials by wildcard/regex.
	"authorization":  {},
	"x-api-key":      {},
	"x-goog-api-key": {},

	// WebSocket handshake headers are generated by the client/dialer.
	"sec-websocket-key":        {},
	"sec-websocket-version":    {},
	"sec-websocket-extensions": {},
}

var headerPassthroughRegexCache sync.Map // map[string]*regexp.Regexp

func getHeaderPassthroughRegex(pattern string) (*regexp.Regexp, error) {
	pattern = strings.TrimSpace(pattern)
	if pattern == "" {
		return nil, errors.New("empty regex pattern")
	}
	if v, ok := headerPassthroughRegexCache.Load(pattern); ok {
		if re, ok := v.(*regexp.Regexp); ok {
			return re, nil
		}
		headerPassthroughRegexCache.Delete(pattern)
	}
	compiled, err := regexp.Compile(pattern)
	if err != nil {
		return nil, err
	}
	actual, _ := headerPassthroughRegexCache.LoadOrStore(pattern, compiled)
	if re, ok := actual.(*regexp.Regexp); ok {
		return re, nil
	}
	return compiled, nil
}

func IsHeaderPassthroughRuleKey(key string) bool {
	return isHeaderPassthroughRuleKey(key)
}
func isHeaderPassthroughRuleKey(key string) bool {
	key = strings.TrimSpace(key)
	if key == "" {
		return false
	}
	if key == headerPassthroughAllKey {
		return true
	}
	lower := strings.ToLower(key)
	return strings.HasPrefix(lower, headerPassthroughRegexPrefix) || strings.HasPrefix(lower, headerPassthroughRegexPrefixV2)
}

func shouldSkipPassthroughHeader(name string) bool {
	name = strings.TrimSpace(name)
	if name == "" {
		return true
	}
	lower := strings.ToLower(name)
	if _, ok := passthroughSkipHeaderNamesLower[lower]; ok {
		return true
	}
	return false
}

func applyHeaderOverridePlaceholders(template string, c *gin.Context, apiKey string) (string, bool, error) {
	trimmed := strings.TrimSpace(template)
	if strings.HasPrefix(trimmed, clientHeaderPlaceholderPrefix) {
		afterPrefix := trimmed[len(clientHeaderPlaceholderPrefix):]
		end := strings.Index(afterPrefix, "}")
		if end < 0 || end != len(afterPrefix)-1 {
			return "", false, fmt.Errorf("client_header placeholder must be the full value: %q", template)
		}

		name := strings.TrimSpace(afterPrefix[:end])
		if name == "" {
			return "", false, fmt.Errorf("client_header placeholder name is empty: %q", template)
		}
		if c == nil || c.Request == nil {
			return "", false, fmt.Errorf("missing request context for client_header placeholder")
		}
		clientHeaderValue := c.Request.Header.Get(name)
		if strings.TrimSpace(clientHeaderValue) == "" {
			return "", false, nil
		}
		// Do not interpolate {api_key} inside client-supplied content.
		return clientHeaderValue, true, nil
	}

	if strings.Contains(template, "{api_key}") {
		template = strings.ReplaceAll(template, "{api_key}", apiKey)
	}
	if strings.TrimSpace(template) == "" {
		return "", false, nil
	}
	return template, true, nil
}

// processHeaderOverride applies channel header overrides, with placeholder substitution.
// Supported placeholders:
//   - {api_key}: resolved to the channel API key
//   - {client_header:<name>}: resolved to the incoming request header value
//
// Header passthrough rules (keys only; values are ignored):
//   - "*": passthrough all incoming headers by name (excluding unsafe headers)
//   - "re:<regex>" / "regex:<regex>": passthrough headers whose names match the regex (Go regexp)
//
// Passthrough rules are applied first, then normal overrides are applied, so explicit overrides win.
func processHeaderOverride(info *common.RelayInfo, c *gin.Context) (map[string]string, error) {
	headerOverride := make(map[string]string)
	if info == nil {
		return headerOverride, nil
	}

	headerOverrideSource := common.GetEffectiveHeaderOverride(info)

	passAll := false
	var passthroughRegex []*regexp.Regexp
	if !info.IsChannelTest {
		for k := range headerOverrideSource {
			key := strings.TrimSpace(strings.ToLower(k))
			if key == "" {
				continue
			}
			if key == headerPassthroughAllKey {
				passAll = true
				continue
			}

			var pattern string
			switch {
			case strings.HasPrefix(key, headerPassthroughRegexPrefix):
				pattern = strings.TrimSpace(key[len(headerPassthroughRegexPrefix):])
			case strings.HasPrefix(key, headerPassthroughRegexPrefixV2):
				pattern = strings.TrimSpace(key[len(headerPassthroughRegexPrefixV2):])
			default:
				continue
			}

			if pattern == "" {
				return nil, types.NewError(fmt.Errorf("header passthrough regex pattern is empty: %q", k), types.ErrorCodeChannelHeaderOverrideInvalid)
			}
			compiled, err := getHeaderPassthroughRegex(pattern)
			if err != nil {
				return nil, types.NewError(err, types.ErrorCodeChannelHeaderOverrideInvalid)
			}
			passthroughRegex = append(passthroughRegex, compiled)
		}
	}

	if passAll || len(passthroughRegex) > 0 {
		if c == nil || c.Request == nil {
			return nil, types.NewError(fmt.Errorf("missing request context for header passthrough"), types.ErrorCodeChannelHeaderOverrideInvalid)
		}
		for name := range c.Request.Header {
			if shouldSkipPassthroughHeader(name) {
				continue
			}
			if !passAll {
				matched := false
				for _, re := range passthroughRegex {
					if re.MatchString(name) {
						matched = true
						break
					}
				}
				if !matched {
					continue
				}
			}
			value := strings.TrimSpace(c.Request.Header.Get(name))
			if value == "" {
				continue
			}
			headerOverride[strings.ToLower(strings.TrimSpace(name))] = value
		}
	}

	for k, v := range headerOverrideSource {
		if isHeaderPassthroughRuleKey(k) {
			continue
		}
		key := strings.TrimSpace(strings.ToLower(k))
		if key == "" {
			continue
		}

		str, ok := v.(string)
		if !ok {
			return nil, types.NewError(nil, types.ErrorCodeChannelHeaderOverrideInvalid)
		}
		if info.IsChannelTest && strings.HasPrefix(strings.TrimSpace(str), clientHeaderPlaceholderPrefix) {
			continue
		}

		value, include, err := applyHeaderOverridePlaceholders(str, c, info.ApiKey)
		if err != nil {
			return nil, types.NewError(err, types.ErrorCodeChannelHeaderOverrideInvalid)
		}
		if !include {
			continue
		}

		headerOverride[key] = value
	}
	return headerOverride, nil
}

func ResolveHeaderOverride(info *common.RelayInfo, c *gin.Context) (map[string]string, error) {
	return processHeaderOverride(info, c)
}

func applyHeaderOverrideToRequest(req *http.Request, headerOverride map[string]string) {
	if req == nil {
		return
	}
	for key, value := range headerOverride {
		req.Header.Set(key, value)
		// set Host in req
		if strings.EqualFold(key, "Host") {
			req.Host = value
		}
	}
}

func DoApiRequest(a Adaptor, c *gin.Context, info *common.RelayInfo, requestBody io.Reader) (*http.Response, error) {
	fullRequestURL, err := a.GetRequestURL(info)
	if err != nil {
		return nil, fmt.Errorf("get request url failed: %w", err)
	}
	logger.LogDebug(c, "fullRequestURL: %s", fullRequestURL)
	req, err := http.NewRequest(c.Request.Method, fullRequestURL, requestBody)
	if err != nil {
		return nil, fmt.Errorf("new request failed: %w", err)
	}
	applyUpstreamContentLength(req, info)
	headers := req.Header
	err = a.SetupRequestHeader(c, &headers, info)
	if err != nil {
		return nil, fmt.Errorf("setup request header failed: %w", err)
	}
	// 在 SetupRequestHeader 之后应用 Header Override，确保用户设置优先级最高
	// 这样可以覆盖默认的 Authorization header 设置
	headerOverride, err := processHeaderOverride(info, c)
	if err != nil {
		return nil, err
	}
	applyHeaderOverrideToRequest(req, headerOverride)
	// 最终安全网：清理 tools schema null + content blocks 格式修复
	sanitizeRequestFinal(req)
	resp, err := doRequest(c, req, info)
	if err != nil {
		return nil, fmt.Errorf("do request failed: %w", err)
	}
	return resp, nil
}

func DoFormRequest(a Adaptor, c *gin.Context, info *common.RelayInfo, requestBody io.Reader) (*http.Response, error) {
	fullRequestURL, err := a.GetRequestURL(info)
	if err != nil {
		return nil, fmt.Errorf("get request url failed: %w", err)
	}
	logger.LogDebug(c, "fullRequestURL: %s", fullRequestURL)
	req, err := http.NewRequest(c.Request.Method, fullRequestURL, requestBody)
	if err != nil {
		return nil, fmt.Errorf("new request failed: %w", err)
	}
	applyUpstreamContentLength(req, info)
	// set form data
	req.Header.Set("Content-Type", c.Request.Header.Get("Content-Type"))
	headers := req.Header
	err = a.SetupRequestHeader(c, &headers, info)
	if err != nil {
		return nil, fmt.Errorf("setup request header failed: %w", err)
	}
	// 在 SetupRequestHeader 之后应用 Header Override，确保用户设置优先级最高
	// 这样可以覆盖默认的 Authorization header 设置
	headerOverride, err := processHeaderOverride(info, c)
	if err != nil {
		return nil, err
	}
	applyHeaderOverrideToRequest(req, headerOverride)
	resp, err := doRequest(c, req, info)
	if err != nil {
		return nil, fmt.Errorf("do request failed: %w", err)
	}
	return resp, nil
}

func DoWssRequest(a Adaptor, c *gin.Context, info *common.RelayInfo, requestBody io.Reader) (*websocket.Conn, error) {
	fullRequestURL, err := a.GetRequestURL(info)
	if err != nil {
		return nil, fmt.Errorf("get request url failed: %w", err)
	}
	targetHeader := http.Header{}
	err = a.SetupRequestHeader(c, &targetHeader, info)
	if err != nil {
		return nil, fmt.Errorf("setup request header failed: %w", err)
	}
	// 在 SetupRequestHeader 之后应用 Header Override，确保用户设置优先级最高
	// 这样可以覆盖默认的 Authorization header 设置
	headerOverride, err := processHeaderOverride(info, c)
	if err != nil {
		return nil, err
	}
	for key, value := range headerOverride {
		targetHeader.Set(key, value)
	}
	targetHeader.Set("Content-Type", c.Request.Header.Get("Content-Type"))
	targetConn, _, err := websocket.DefaultDialer.Dial(fullRequestURL, targetHeader)
	if err != nil {
		return nil, fmt.Errorf("dial failed to %s: %w", fullRequestURL, err)
	}
	// send request body
	//all, err := io.ReadAll(requestBody)
	//err = service.WssString(c, targetConn, string(all))
	return targetConn, nil
}

func startPingKeepAlive(c *gin.Context, pingInterval time.Duration) context.CancelFunc {
	pingerCtx, stopPinger := context.WithCancel(context.Background())

	gopool.Go(func() {
		defer func() {
			// 增加panic恢复处理
			if r := recover(); r != nil {
				logger.LogDebug(c, "SSE ping goroutine panic recovered: %v", r)
			}
			logger.LogDebug(c, "SSE ping goroutine stopped")
		}()

		if pingInterval <= 0 {
			pingInterval = helper.DefaultPingInterval
		}

		ticker := time.NewTicker(pingInterval)
		// 确保在任何情况下都清理ticker
		defer func() {
			ticker.Stop()
			logger.LogDebug(c, "SSE ping ticker stopped")
		}()

		var pingMutex sync.Mutex
		logger.LogDebug(c, "SSE ping goroutine started")

		// 增加超时控制，防止goroutine长时间运行
		maxPingDuration := 120 * time.Minute // 最大ping持续时间
		pingTimeout := time.NewTimer(maxPingDuration)
		defer pingTimeout.Stop()

		for {
			select {
			// 发送 ping 数据
			case <-ticker.C:
				if err := sendPingData(c, &pingMutex); err != nil {
					logger.LogDebug(c, "SSE ping error, stopping goroutine: %s", err.Error())
					return
				}
			// 收到退出信号
			case <-pingerCtx.Done():
				return
			// request 结束
			case <-c.Request.Context().Done():
				return
			// 超时保护，防止goroutine无限运行
			case <-pingTimeout.C:
				logger.LogDebug(c, "SSE ping goroutine timeout, stopping")
				return
			}
		}
	})

	return stopPinger
}

func sendPingData(c *gin.Context, mutex *sync.Mutex) error {
	// 增加超时控制，防止锁死等待
	done := make(chan error, 1)
	go func() {
		mutex.Lock()
		defer mutex.Unlock()

		err := helper.PingData(c)
		if err != nil {
			logger.LogError(c, "SSE ping error: "+err.Error())
			done <- err
			return
		}

		logger.LogDebug(c, "SSE ping data sent")
		done <- nil
	}()

	// 设置发送ping数据的超时时间
	select {
	case err := <-done:
		return err
	case <-time.After(10 * time.Second):
		return errors.New("SSE ping data send timeout")
	case <-c.Request.Context().Done():
		return errors.New("request context cancelled during ping")
	}
}

func DoRequest(c *gin.Context, req *http.Request, info *common.RelayInfo) (*http.Response, error) {
	return doRequest(c, req, info)
}
func doRequest(c *gin.Context, req *http.Request, info *common.RelayInfo) (*http.Response, error) {
	var client *http.Client
	var err error
	if info.ChannelSetting.Proxy != "" {
		client, err = service.NewProxyHttpClient(info.ChannelSetting.Proxy)
		if err != nil {
			return nil, fmt.Errorf("new proxy http client failed: %w", err)
		}
	} else {
		client = service.GetHttpClient()
	}

	// Headroom 压缩：在发送请求前，如果启用了 Headroom，对请求体进行压缩
	// 支持所有带 messages 字段的请求（Chat/Completions/Claude Messages/Responses）
	if operation_setting.HeadroomGlobalEnabled && info.ChannelSetting.HeadroomEnabled &&
		(info.RelayMode == constant.RelayModeChatCompletions ||
			info.RelayMode == constant.RelayModeCompletions ||
			info.RelayMode == constant.RelayModeResponses ||
			info.RelayMode == constant.RelayModeUnknown ||
			info.RelayFormat == types.RelayFormatClaude) {
		// 优先级：渠道配置 HeadroomURL > 环境变量 HEADROOM_URL > 默认值
		headroomURL := info.ChannelSetting.HeadroomURL
		if headroomURL == "" {
			headroomURL = os.Getenv("HEADROOM_URL")
		}
		if headroomURL == "" {
			headroomURL = "http://127.0.0.1:8787"
		}

		// 读取原始请求体；后续无论压缩是否成功，都必须恢复 req.Body
		bodyBytes, readErr := io.ReadAll(req.Body)
		req.Body.Close()
		if readErr == nil && len(bodyBytes) > 0 {
			// 默认透传原请求，只有压缩成功且 tokens_saved > 0 时才替换 body
			req.Body = io.NopCloser(bytes.NewReader(bodyBytes))
			req.ContentLength = int64(len(bodyBytes))

			compressURL := fmt.Sprintf("%s/v1/compress", strings.TrimRight(headroomURL, "/"))
			// 超时 15 秒：大请求（>50 万 token）的 Kompress ML 推理需要较长时间
			compressClient := &http.Client{Timeout: 15 * time.Second}
			compressResp, compressErr := compressClient.Post(compressURL, "application/json", bytes.NewReader(bodyBytes))
			if compressErr == nil && compressResp != nil {
				defer compressResp.Body.Close()
				if compressResp.StatusCode == http.StatusOK {
					var compressResult struct {
						Messages         json.RawMessage `json:"messages"`
						TokensBefore     int             `json:"tokens_before"`
						TokensAfter      int             `json:"tokens_after"`
						TokensSaved      int             `json:"tokens_saved"`
						CompressionRatio float64         `json:"compression_ratio"`
					}
					if decodeErr := common2.DecodeJson(compressResp.Body, &compressResult); decodeErr == nil {
						// 即使 tokens_saved=0（noop），也记录 headroom_input 到日志，便于统计压缩覆盖率。
						// 用 new-api 自己的 tokenizer 重算，与压缩成功分支口径一致。
						var origMsgsForCount interface{}
						if common2.Unmarshal(bodyBytes, &origMsgsForCount) == nil {
							var origMsgsSlice interface{}
							if m, ok := origMsgsForCount.(map[string]interface{}); ok {
								origMsgsSlice = m["messages"]
							}
							modelName := info.UpstreamModelName
							if modelName == "" {
								modelName = info.OriginModelName
							}
							if tc := service.CountTokenInput(origMsgsSlice, modelName); tc > 0 {
								info.HeadroomTokensInput = tc
							} else if compressResult.TokensBefore > 0 {
								info.HeadroomTokensInput = compressResult.TokensBefore
							}
						} else if compressResult.TokensBefore > 0 {
							info.HeadroomTokensInput = compressResult.TokensBefore
						}
					if compressResult.TokensSaved > 0 {
						var originalBody map[string]interface{}
						if common2.Unmarshal(bodyBytes, &originalBody) == nil {
							var compressedMsgs interface{}
							if common2.Unmarshal(compressResult.Messages, &compressedMsgs) == nil {
								// 修复：headroom 压缩可能把 content blocks 格式破坏
								// 遍历每条消息，确保 content 格式与上游 API 兼容：
								//  - content 是数组时，每个元素必须是 dict 且含 type 字段
								//  - 原始 content 是字符串时，压缩后也还原成字符串
							    if compressedMsgsList, ok := compressedMsgs.([]interface{}); ok {
									origMsgs, _ := originalBody["messages"].([]interface{})
									for i, msg := range compressedMsgsList {
										msgMap, ok := msg.(map[string]interface{})
										if !ok {
											continue
										}
										compressedContent := msgMap["content"]

										// 先确定原始 content 类型
										origContentIsString := false
										if i < len(origMsgs) {
											if origMsgMap, ok := origMsgs[i].(map[string]interface{}); ok {
												if _, isStr := origMsgMap["content"].(string); isStr {
													origContentIsString = true
												}
											}
										}

										// 情况1: 原始 content 是字符串 -> 压缩后也必须是字符串
										if origContentIsString {
											switch cc := compressedContent.(type) {
											case string:
												// 已经是字符串，无需处理
											case []interface{}:
												// 压缩后变成了数组，提取所有 text 拼接回字符串
												var texts []string
												for _, block := range cc {
													switch b := block.(type) {
													case string:
														texts = append(texts, b)
													case map[string]interface{}:
														if text, ok := b["text"].(string); ok {
															texts = append(texts, text)
														}
													}
												}
												if len(texts) > 0 {
													msgMap["content"] = strings.Join(texts, "\n")
												}
											case nil:
												// content 为 nil，保持
											}
											continue
										}

										// 情况2: 原始 content 是数组（content blocks）
										// 压缩后必须是数组，每个元素必须是 dict 且含 type 字段
										switch cc := compressedContent.(type) {
										case string:
											// 压缩后变成了字符串，包装回 content block
											msgMap["content"] = []interface{}{
												map[string]interface{}{
													"type": "text",
													"text": cc,
												},
											}
										case []interface{}:
											fixedArr := make([]interface{}, 0, len(cc))
											for _, block := range cc {
												switch b := block.(type) {
												case string:
													fixedArr = append(fixedArr, map[string]interface{}{
														"type": "text",
														"text": b,
													})
												case map[string]interface{}:
													if _, hasType := b["type"]; !hasType {
														b["type"] = "text"
													}
													// 确保有 text 字段（type=text 时必须有）
													if b["type"] == "text" {
														if _, hasText := b["text"]; !hasText {
															b["text"] = ""
														}
													}
													fixedArr = append(fixedArr, b)
												case float64, int, int64, bool:
													// 基本类型，包装成 text block
													fixedArr = append(fixedArr, map[string]interface{}{
														"type": "text",
														"text": fmt.Sprintf("%v", b),
													})
												default:
													// 未知类型，跳过（避免发送无效数据导致 400）
												}
											}
											msgMap["content"] = fixedArr
										case nil:
											// content 为 nil，保持
										}
									}
								}
								// 压缩前 messages 会被下一行覆盖，先捕获以便同口径重算 token
								origMsgsSnapshot := originalBody["messages"]
								originalBody["messages"] = compressedMsgs
								newBodyBytes, marshalErr := common2.Marshal(originalBody)
								if marshalErr == nil {
									req.Body = io.NopCloser(bytes.NewReader(newBodyBytes))
									req.ContentLength = int64(len(newBodyBytes))
									// 用 new-api 自己的 tokenizer（按模型选择 codec/估算）重算压缩前后 token，
									// 覆盖压缩服务返回的 cl100k 口径值。压缩服务用 cl100k 量，上游用各自模型
									// tokenizer 量，口径不一致导致看板"真实节省率"出现负数。
									// 重算后 before/after 都用 new-api tokenizer，比值自洽，不再跨口径比较。
									modelName := info.UpstreamModelName
									if modelName == "" {
										modelName = info.OriginModelName
									}
									tokenBefore := service.CountTokenInput(origMsgsSnapshot, modelName)
									tokenAfter := service.CountTokenInput(compressedMsgs, modelName)
									if tokenBefore > 0 && tokenAfter >= 0 && tokenAfter <= tokenBefore {
										info.HeadroomTokensInput = tokenBefore
										info.HeadroomTokensSaved = tokenBefore - tokenAfter
										info.HeadroomRatio = float64(tokenBefore-tokenAfter) / float64(tokenBefore)
									} else {
										// 重算异常时回退到压缩服务自报值（cl100k 口径）
										info.HeadroomTokensSaved = compressResult.TokensSaved
										if compressResult.TokensBefore > 0 {
											info.HeadroomTokensInput = compressResult.TokensBefore
											info.HeadroomRatio = float64(compressResult.TokensSaved) / float64(compressResult.TokensBefore)
										} else {
											info.HeadroomRatio = compressResult.CompressionRatio
										}
									}
									logger.LogInfo(c, fmt.Sprintf("headroom compression: %d -> %d tokens (re-counted by %s), saved %d (%.1f%%)",
										tokenBefore, tokenAfter, modelName, info.HeadroomTokensSaved, info.HeadroomRatio*100))
								}
							}
						}
					} else {
						// noop: headroom 判定不需要压缩，记录原因
						logger.LogInfo(c, fmt.Sprintf("headroom noop: tokens_before=%d, no compression needed", compressResult.TokensBefore))
					}
					}
				} else {
					logger.LogInfo(c, fmt.Sprintf("headroom compression bad status: %d, using original body", compressResp.StatusCode))
			}
		} else if compressErr != nil {
			logger.LogInfo(c, fmt.Sprintf("headroom compression failed: %v, using original body", compressErr))
		}
		} else {
			if bodyBytes != nil {
				req.Body = io.NopCloser(bytes.NewReader(bodyBytes))
				req.ContentLength = int64(len(bodyBytes))
			}
		}
	}

	// ========== content blocks 格式安全网 ==========
	// 无论是否经过 headroom 压缩，发送前都对 messages 做一次格式校验
	// 防止 content 是数组但元素不是 dict 或缺少 type 字段导致上游 400
	// 同时清理 tools schema 中的 null 值（required/enum 等字段 null -> []）
	if req.Body != nil {
		safeBody, changed := sanitizeRequestBody(req)
		if changed {
			req.Body = io.NopCloser(bytes.NewReader(safeBody))
			req.ContentLength = int64(len(safeBody))
		}
	}

	var stopPinger context.CancelFunc
	if info.IsStream {
		helper.SetEventStreamHeaders(c)
		// 处理流式请求的 ping 保活
		generalSettings := operation_setting.GetGeneralSetting()
		if generalSettings.PingIntervalEnabled && !info.DisablePing {
			pingInterval := time.Duration(generalSettings.PingIntervalSeconds) * time.Second
			stopPinger = startPingKeepAlive(c, pingInterval)
			// 使用defer确保在任何情况下都能停止ping goroutine
			defer func() {
				if stopPinger != nil {
					stopPinger()
					logger.LogDebug(c, "SSE ping goroutine stopped by defer")
				}
			}()
		}
	}

	resp, err := client.Do(req)
	if err != nil {
		logger.LogError(c, "do request failed: "+err.Error())
		return nil, types.NewError(err, types.ErrorCodeDoRequestFailed, types.ErrOptionWithHideErrMsg("upstream error: do request failed"))
	}
	if resp == nil {
		return nil, errors.New("resp is nil")
	}

	if upID := resp.Header.Get(common2.RequestIdKey); upID != "" {
		c.Set(common2.UpstreamRequestIdKey, upID)
	}

	_ = req.Body.Close()
	_ = c.Request.Body.Close()
	return resp, nil
}

// sanitizeRequestFinal 最终安全网，在任何请求发出前清理 body
func sanitizeRequestFinal(req *http.Request) {
	if req.Body == nil {
		return
	}
	safeBody, changed := sanitizeRequestBody(req)
	if changed {
		req.Body = io.NopCloser(bytes.NewReader(safeBody))
		req.ContentLength = int64(len(safeBody))
		req.Header.Set("Content-Length", fmt.Sprintf("%d", len(safeBody)))
	}
}

// sanitizeRequestBody 在发送请求前做最终格式安全网：
// 1. messages content blocks 格式校验（确保数组元素是 dict 且含 type）
// 2. tools schema null 清理（required/enum 等 null -> []）
func sanitizeRequestBody(req *http.Request) ([]byte, bool) {
	if req.Body == nil {
		return nil, false
	}
	bodyBytes, err := io.ReadAll(req.Body)
	req.Body.Close()
	if err != nil || len(bodyBytes) == 0 {
		req.Body = io.NopCloser(bytes.NewReader(bodyBytes))
		return bodyBytes, false
	}

	var body map[string]interface{}
	if common2.Unmarshal(bodyBytes, &body) != nil {
		req.Body = io.NopCloser(bytes.NewReader(bodyBytes))
		return bodyBytes, false
	}

	changed := false

	// 1. 清理 tools schema 中的 null 值（始终执行，不依赖 DeepEqual）
	if tools, exists := body["tools"]; exists && tools != nil {
		body["tools"] = sanitizeToolsSchemaNulls(tools)
		changed = true
	}

	// 2. 修复 messages content blocks 格式
	if msgs, ok := body["messages"].([]interface{}); ok {
		for _, msg := range msgs {
			msgMap, ok := msg.(map[string]interface{})
			if !ok {
				continue
			}
			switch content := msgMap["content"].(type) {
			case []interface{}:
				fixedArr := make([]interface{}, 0, len(content))
				for _, block := range content {
					switch b := block.(type) {
					case map[string]interface{}:
						if _, hasType := b["type"]; !hasType {
							b["type"] = "text"
							changed = true
						}
						if b["type"] == "text" {
							if _, hasText := b["text"]; !hasText {
								b["text"] = ""
								changed = true
							}
						}
						fixedArr = append(fixedArr, b)
					case string:
						fixedArr = append(fixedArr, map[string]interface{}{
							"type": "text",
							"text": b,
						})
						changed = true
					default:
						fixedArr = append(fixedArr, map[string]interface{}{
							"type": "text",
							"text": fmt.Sprintf("%v", b),
						})
						changed = true
					}
				}
				msgMap["content"] = fixedArr
			}
		}
	}

	if !changed {
		req.Body = io.NopCloser(bytes.NewReader(bodyBytes))
		return bodyBytes, false
	}

	newBody, err := common2.Marshal(body)
	if err != nil {
		req.Body = io.NopCloser(bytes.NewReader(bodyBytes))
		return bodyBytes, false
	}
	return newBody, true
}

// sanitizeToolsSchemaNulls 递归清理 tools schema 中的 null 值
func sanitizeToolsSchemaNulls(v interface{}) interface{} {
	switch val := v.(type) {
	case map[string]interface{}:
		result := make(map[string]interface{}, len(val))
		for k, child := range val {
			if child == nil {
				if k == "required" || k == "enum" || k == "items" || k == "prefixItems" {
					result[k] = []interface{}{}
				}
				continue
			}
			result[k] = sanitizeToolsSchemaNulls(child)
		}
		return result
	case []interface{}:
		for i, item := range val {
			val[i] = sanitizeToolsSchemaNulls(item)
		}
		return val
	default:
		return v
	}
}

func sanitizeMessagesContentBlocks(req *http.Request) ([]byte, bool) {
	return sanitizeRequestBody(req)
}

func DoTaskApiRequest(a TaskAdaptor, c *gin.Context, info *common.RelayInfo, requestBody io.Reader) (*http.Response, error) {
	fullRequestURL, err := a.BuildRequestURL(info)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequest(c.Request.Method, fullRequestURL, requestBody)
	if err != nil {
		return nil, fmt.Errorf("new request failed: %w", err)
	}
	applyUpstreamContentLength(req, info)
	req.GetBody = func() (io.ReadCloser, error) {
		return io.NopCloser(requestBody), nil
	}

	err = a.BuildRequestHeader(c, req, info)
	if err != nil {
		return nil, fmt.Errorf("setup request header failed: %w", err)
	}
	resp, err := doRequest(c, req, info)
	if err != nil {
		return nil, fmt.Errorf("do request failed: %w", err)
	}
	return resp, nil
}
